from pathlib import Path
from typing import overload

import numpy as np

from ._core import Board as Board
from ._core import RustValueModel as RustValueModel
from . import dataloader as dataloader
from . import model as model

__all__: list[str]

class RecordedBoard:
    @staticmethod
    def new_initial() -> RecordedBoard: ...
    @property
    def start_board(self) -> Board: ...
    @property
    def current_board(self) -> Board: ...
    @property
    def black_bits(self) -> int: ...
    @property
    def white_bits(self) -> int: ...
    @property
    def side_to_move(self) -> str: ...
    @property
    def moves(self) -> list[int | None]: ...
    def to_bits(self) -> tuple[int, int, str]: ...
    def apply_move(self, square: int) -> RecordedBoard: ...
    def apply_forced_pass(self) -> RecordedBoard: ...
    def generate_legal_moves(self) -> int: ...
    def legal_moves_list(self) -> list[int]: ...
    def is_legal_move(self, square: int) -> bool: ...
    def board_status(self) -> str: ...
    def disc_count(self) -> tuple[int, int, int]: ...
    def game_result(self) -> str: ...
    def final_margin_from_black(self) -> int: ...
    def transform(self, sym: str) -> Board: ...
    def encode_planes(self, history: list[Board], config: dict) -> np.ndarray: ...
    def encode_flat_features(self, history: list[Board], config: dict) -> np.ndarray: ...
    def prepare_cnn_model_input(self) -> np.ndarray: ...
    def prepare_flat_model_input(self) -> np.ndarray: ...
    def prepare_nnue_model_input(self) -> np.ndarray: ...
    def search_best_move_exact(
        self,
        timeout_seconds: float = 1.0,
        *,
        worker_count: int | None = None,
        serial_fallback_empty_threshold: int = 18,
        shared_tt_empty_threshold: int = 20,
    ) -> dict[str, object]: ...
    def select_move_with_model(
        self,
        model: object,
        depth: int = 1,
        timeout_seconds: float = 1.0,
        *,
        policy_mode: str = "best",
        search_mode: str = "fixed",
        device: str = "cpu",
        exact_from_empty_threshold: int | None = 16,
        always_try_exact: bool = False,
    ) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    def finish(self) -> dict[str, object]: ...
    def save_record(self, path: str) -> None: ...

class RecordDataset:
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def __getitem__(self, global_index: int) -> dict[str, object]: ...
    def get(self, global_index: int) -> dict[str, object]: ...
    def get_cnn_input(self, global_index: int) -> np.ndarray: ...
    def get_flat_input(self, global_index: int) -> np.ndarray: ...
    def get_nnue_input(self, global_index: int) -> np.ndarray: ...
    def get_targets(self, global_index: int) -> dict[str, object]: ...

class BalancedOpeningSet:
    def __init__(self, entries: list[dict[str, object]], boards: list[Board]) -> None: ...
    def __len__(self) -> int: ...
    @property
    def entries(self) -> list[dict[str, object]]: ...
    @property
    def boards(self) -> list[Board]: ...

def initial_board() -> Board: ...
def board_from_bits(black_bits: int, white_bits: int, side_to_move: str) -> Board: ...
def all_symmetries() -> list[str]: ...
def validate_board(board_or_record: Board | RecordedBoard) -> None: ...
def generate_legal_moves(board_or_record: Board | RecordedBoard) -> int: ...
def legal_moves_list(board_or_record: Board | RecordedBoard) -> list[int]: ...
def is_legal_move(board_or_record: Board | RecordedBoard, square: int) -> bool: ...
@overload
def apply_move(board_or_record: Board, square: int) -> Board: ...
@overload
def apply_move(board_or_record: RecordedBoard, square: int) -> RecordedBoard: ...
@overload
def apply_forced_pass(board_or_record: Board) -> Board: ...
@overload
def apply_forced_pass(board_or_record: RecordedBoard) -> RecordedBoard: ...
def board_status(board_or_record: Board | RecordedBoard) -> str: ...
def disc_count(board_or_record: Board | RecordedBoard) -> tuple[int, int, int]: ...
def game_result(board_or_record: Board | RecordedBoard) -> str: ...
def final_margin_from_black(board_or_record: Board | RecordedBoard) -> int: ...
def pack_board(board_or_record: Board | RecordedBoard) -> tuple[int, int, str]: ...
def unpack_board(packed: tuple[int, int, str]) -> Board: ...
def play_random_game(seed: int, config: dict) -> dict: ...
def random_start_board(plies: int, seed: int) -> Board: ...
def sample_reachable_positions(seed: int, config: dict) -> list[Board]: ...
def generate_balanced_opening_file(
    model: object,
    path: str | Path,
    *,
    plies: int = 8,
    threshold: float = 2 / 64,
    value_scale: str = "normalized",
    batch_size: int = 1024,
    dedupe_symmetry: bool = True,
    device: str = "cpu",
) -> dict[str, object]: ...
def load_balanced_opening_file(
    path: str | Path,
    *,
    validate: bool = True,
) -> BalancedOpeningSet: ...
def random_balanced_opening_board(
    path_or_set: str | Path | BalancedOpeningSet, seed: int
) -> Board: ...
def start_game_recording(start_board: Board) -> RecordedBoard: ...
def record_move(record: RecordedBoard, square: int) -> RecordedBoard: ...
def record_pass(record: RecordedBoard) -> RecordedBoard: ...
def current_board(record: RecordedBoard) -> Board: ...
def finish_game_recording(record: RecordedBoard) -> dict[str, object]: ...
def append_game_record(path: str, record: RecordedBoard | dict[str, object]) -> None: ...
def load_game_records(path: str) -> list[dict[str, object]]: ...
def open_game_record_dataset(paths: str | Path | list[str | Path]) -> RecordDataset: ...
def get_dataloader(
    paths: str | Path | list[str | Path],
    batch_size: int,
    *,
    mode: str = "value_only",
    shuffle: bool = True,
    num_workers: int = 0,
    drop_last: bool = False,
    pin_memory: bool = False,
) -> object: ...
def supervised_examples_from_trace(trace: dict) -> list[dict[str, object]]: ...
def supervised_examples_from_traces(traces: list[dict]) -> list[dict[str, object]]: ...
def packed_supervised_examples_from_trace(trace: dict) -> list[dict[str, object]]: ...
def packed_supervised_examples_from_traces(traces: list[dict]) -> list[dict[str, object]]: ...
def prepare_planes_learning_batch(examples: list[dict], config: dict) -> dict[str, np.ndarray]: ...
def prepare_flat_learning_batch(examples: list[dict], config: dict) -> dict[str, np.ndarray]: ...
def prepare_cnn_model_input(board_or_record: Board | RecordedBoard) -> np.ndarray: ...
def prepare_cnn_model_input_batch(values: list[Board | RecordedBoard]) -> np.ndarray: ...
def prepare_flat_model_input(board_or_record: Board | RecordedBoard) -> np.ndarray: ...
def prepare_flat_model_input_batch(values: list[Board | RecordedBoard]) -> np.ndarray: ...
def prepare_nnue_model_input(board_or_record: Board | RecordedBoard) -> np.ndarray: ...
def load_model(path: str | Path) -> RustValueModel: ...
def export_model(pth_path: str | Path, vvm_path: str | Path) -> None: ...
def search_best_move_exact(
    board_or_record: Board | RecordedBoard,
    timeout_seconds: float = 1.0,
    *,
    worker_count: int | None = None,
    serial_fallback_empty_threshold: int = 18,
    shared_tt_empty_threshold: int = 20,
) -> dict[str, object]: ...
def select_move_with_model(
    board_or_record: Board | RecordedBoard,
    model: object,
    depth: int = 1,
    timeout_seconds: float = 1.0,
    *,
    policy_mode: str = "best",
    search_mode: str = "fixed",
    device: str = "cpu",
    exact_from_empty_threshold: int | None = 16,
    always_try_exact: bool = False,
) -> dict[str, object]: ...
def encode_planes(board: Board, history: list[Board], config: dict) -> np.ndarray: ...
def encode_planes_batch(
    boards: list[Board], histories: list[list[Board]], config: dict
) -> np.ndarray: ...
def encode_flat_features(board: Board, history: list[Board], config: dict) -> np.ndarray: ...
def encode_flat_features_batch(
    boards: list[Board], histories: list[list[Board]], config: dict
) -> np.ndarray: ...
def transform_board(board: Board, sym: str) -> Board: ...
def transform_square(square: int, sym: str) -> int: ...
