from pathlib import Path
from typing import overload

import numpy as np

from ._core import (
    Board,
    all_symmetries,
    board_from_bits,
    initial_board,
    transform_board,
    transform_square,
)


class RecordedBoard:
    @property
    def start_board(self) -> Board: ...
    @property
    def current_board(self) -> Board: ...
    @property
    def black_bits(self) -> int: ...
    @property
    def white_bits(self) -> int: ...
    @property
    def side_to_move(self) -> str: ...
    @property
    def moves(self) -> list[int | None]: ...
    def to_bits(self) -> tuple[int, int, str]: ...
    def apply_move(self, square: int) -> RecordedBoard: ...
    def apply_forced_pass(self) -> RecordedBoard: ...
    def generate_legal_moves(self) -> int: ...
    def legal_moves_list(self) -> list[int]: ...
    def is_legal_move(self, square: int) -> bool: ...
    def board_status(self) -> str: ...
    def disc_count(self) -> tuple[int, int, int]: ...
    def game_result(self) -> str: ...
    def final_margin_from_black(self) -> int: ...
    def transform(self, sym: str) -> Board: ...
    def encode_planes(self, history: list[Board], config: dict) -> np.ndarray: ...
    def encode_flat_features(self, history: list[Board], config: dict) -> np.ndarray: ...
    def prepare_cnn_model_input(self) -> np.ndarray: ...
    def prepare_flat_model_input(self) -> np.ndarray: ...
    def to_dict(self) -> dict[str, object]: ...
    def finish(self) -> dict[str, object]: ...
    def save_record(self, path: str) -> None: ...


class RecordDataset:
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def __getitem__(self, global_index: int) -> dict[str, object]: ...
    def get(self, global_index: int) -> dict[str, object]: ...
    def get_cnn_input(self, global_index: int) -> np.ndarray: ...
    def get_flat_input(self, global_index: int) -> np.ndarray: ...
    def get_targets(self, global_index: int) -> dict[str, object]: ...


def validate_board(board_or_record: Board | RecordedBoard) -> None: ...
def generate_legal_moves(board_or_record: Board | RecordedBoard) -> int: ...
def legal_moves_list(board_or_record: Board | RecordedBoard) -> list[int]: ...
def is_legal_move(board_or_record: Board | RecordedBoard, square: int) -> bool: ...


@overload
def apply_move(board_or_record: Board, square: int) -> Board: ...


@overload
def apply_move(board_or_record: RecordedBoard, square: int) -> RecordedBoard: ...


@overload
def apply_forced_pass(board_or_record: Board) -> Board: ...


@overload
def apply_forced_pass(board_or_record: RecordedBoard) -> RecordedBoard: ...


def board_status(board_or_record: Board | RecordedBoard) -> str: ...
def disc_count(board_or_record: Board | RecordedBoard) -> tuple[int, int, int]: ...
def game_result(board_or_record: Board | RecordedBoard) -> str: ...
def final_margin_from_black(board_or_record: Board | RecordedBoard) -> int: ...
def pack_board(board_or_record: Board | RecordedBoard) -> tuple[int, int, str]: ...
def unpack_board(packed: tuple[int, int, str]) -> Board: ...

def play_random_game(seed: int, config: dict) -> dict: ...
def random_start_board(plies: int, seed: int) -> Board: ...
def sample_reachable_positions(seed: int, config: dict) -> list[Board]: ...

def start_game_recording(start_board: Board) -> RecordedBoard: ...
def record_move(record: RecordedBoard, square: int) -> RecordedBoard: ...
def record_pass(record: RecordedBoard) -> RecordedBoard: ...
def current_board(record: RecordedBoard) -> Board: ...
def finish_game_recording(record: RecordedBoard) -> dict[str, object]: ...
def append_game_record(path: str, record: RecordedBoard | dict[str, object]) -> None: ...
def load_game_records(path: str) -> list[dict[str, object]]: ...
def open_game_record_dataset(paths: str | Path | list[str | Path]) -> RecordDataset: ...

def supervised_examples_from_trace(trace: dict) -> list[dict[str, object]]: ...
def supervised_examples_from_traces(traces: list[dict]) -> list[dict[str, object]]: ...
def packed_supervised_examples_from_trace(trace: dict) -> list[dict[str, object]]: ...
def packed_supervised_examples_from_traces(traces: list[dict]) -> list[dict[str, object]]: ...
def prepare_planes_learning_batch(examples: list[dict], config: dict) -> dict[str, np.ndarray]: ...
def prepare_flat_learning_batch(examples: list[dict], config: dict) -> dict[str, np.ndarray]: ...

def prepare_cnn_model_input(board_or_record: Board | RecordedBoard) -> np.ndarray: ...
def prepare_cnn_model_input_batch(values: list[Board | RecordedBoard]) -> np.ndarray: ...
def prepare_flat_model_input(board_or_record: Board | RecordedBoard) -> np.ndarray: ...
def prepare_flat_model_input_batch(values: list[Board | RecordedBoard]) -> np.ndarray: ...

def encode_planes(board: Board, history: list[Board], config: dict) -> np.ndarray: ...
def encode_planes_batch(
    boards: list[Board], histories: list[list[Board]], config: dict
) -> np.ndarray: ...
def encode_flat_features(board: Board, history: list[Board], config: dict) -> np.ndarray: ...
def encode_flat_features_batch(
    boards: list[Board], histories: list[list[Board]], config: dict
) -> np.ndarray: ...
