import numpy as np

class Board:
    def __init__(self, black_bits: int, white_bits: int, side_to_move: str) -> None: ...
    @staticmethod
    def new_initial() -> Board: ...
    @property
    def black_bits(self) -> int: ...
    @property
    def white_bits(self) -> int: ...
    @property
    def side_to_move(self) -> str: ...
    def to_bits(self) -> tuple[int, int, str]: ...
    def apply_move(self, square: int) -> Board: ...
    def apply_forced_pass(self) -> Board: ...
    def generate_legal_moves(self) -> int: ...
    def legal_moves_list(self) -> list[int]: ...
    def is_legal_move(self, square: int) -> bool: ...
    def board_status(self) -> str: ...
    def disc_count(self) -> tuple[int, int, int]: ...
    def game_result(self) -> str: ...
    def final_margin_from_black(self) -> int: ...
    def transform(self, sym: str) -> Board: ...
    def encode_planes(self, history: list[Board], config: dict) -> np.ndarray: ...
    def encode_flat_features(self, history: list[Board], config: dict) -> np.ndarray: ...
    def prepare_cnn_model_input(self) -> np.ndarray: ...
    def prepare_flat_model_input(self) -> np.ndarray: ...
    def prepare_nnue_model_input(self) -> np.ndarray: ...
    def search_best_move_exact(
        self,
        timeout_seconds: float = 1.0,
        *,
        worker_count: int | None = None,
        serial_fallback_empty_threshold: int = 18,
        shared_tt_empty_threshold: int = 20,
    ) -> dict[str, object]: ...
    def select_move_with_model(
        self,
        model: object,
        depth: int = 1,
        timeout_seconds: float = 1.0,
        *,
        policy_mode: str = "best",
        search_mode: str = "fixed",
        device: str = "cpu",
        exact_from_empty_threshold: int | None = 16,
        always_try_exact: bool = False,
    ) -> dict[str, object]: ...

class RustValueModel:
    @property
    def accumulator_dim(self) -> int: ...
    @property
    def hidden_dim(self) -> int: ...
    def evaluate_board(self, board: Board) -> float: ...

def initial_board() -> Board: ...
def board_from_bits(black_bits: int, white_bits: int, side_to_move: str) -> Board: ...
def pack_board(board: Board) -> tuple[int, int, str]: ...
def _unpack_board_parts(black_bits: int, white_bits: int, side_to_move: str) -> Board: ...
def _play_random_game_parts(
    seed: int, max_plies: int | None
) -> tuple[list[tuple[int, int, str]], list[int | None], str, int, int, bool]: ...
def _random_start_board_parts(seed: int, plies: int) -> tuple[int, int, str]: ...
def _start_game_recording_parts(
    board: Board,
) -> tuple[tuple[int, int, str], tuple[int, int, str], list[int | None]]: ...
def _record_move_parts(
    start_board_bits: tuple[int, int, str],
    current_board_bits: tuple[int, int, str],
    moves: list[int | None],
    square: int,
) -> tuple[tuple[int, int, str], tuple[int, int, str], list[int | None]]: ...
def _record_pass_parts(
    start_board_bits: tuple[int, int, str],
    current_board_bits: tuple[int, int, str],
    moves: list[int | None],
) -> tuple[tuple[int, int, str], tuple[int, int, str], list[int | None]]: ...
def _finish_game_recording_parts(
    start_board_bits: tuple[int, int, str],
    current_board_bits: tuple[int, int, str],
    moves: list[int | None],
) -> tuple[tuple[int, int, str], list[int | None], str, int, int, int, int]: ...
def _append_game_record_parts(
    path: str,
    start_board_bits: tuple[int, int, str],
    moves: list[int | None],
    final_result: str,
    final_black_discs: int,
    final_white_discs: int,
    final_empty_discs: int,
    final_margin_from_black: int,
) -> None: ...
def _load_game_records_parts(
    path: str,
) -> list[tuple[tuple[int, int, str], list[int | None], str, int, int, int, int]]: ...
def _sample_reachable_positions_parts(
    seed: int, num_positions: int, min_plies: int, max_plies: int
) -> list[tuple[int, int, str]]: ...
def _supervised_examples_from_trace_parts(
    boards_bits: list[tuple[int, int, str]],
    moves: list[int | None],
    final_result: str,
    final_margin_from_black: int,
    plies_played: int,
    reached_terminal: bool,
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int]]: ...
def _supervised_examples_from_traces_parts(
    traces: list[tuple[list[tuple[int, int, str]], list[int | None], str, int, int, bool]],
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int]]: ...
def _packed_supervised_examples_from_trace_parts(
    boards_bits: list[tuple[int, int, str]],
    moves: list[int | None],
    final_result: str,
    final_margin_from_black: int,
    plies_played: int,
    reached_terminal: bool,
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]]: ...
def _packed_supervised_examples_from_traces_parts(
    traces: list[tuple[list[tuple[int, int, str]], list[int | None], str, int, int, bool]],
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]]: ...
def _prepare_planes_learning_batch_parts(
    examples: list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
def _prepare_flat_learning_batch_parts(
    examples: list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
def _encode_planes_parts(
    board: Board,
    history: list[Board],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def _encode_planes_batch_parts(
    boards: list[Board],
    histories: list[list[Board]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def _encode_flat_features_parts(
    board: Board,
    history: list[Board],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def _encode_flat_features_batch_parts(
    boards: list[Board],
    histories: list[list[Board]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def _prepare_nnue_model_input_parts(board: Board) -> np.ndarray: ...
def _load_rust_value_model(path: str) -> RustValueModel: ...
def _search_best_move_exact_parts(
    board: Board,
    timeout_seconds: float,
    worker_count: int | None,
    serial_fallback_empty_threshold: int,
    shared_tt_empty_threshold: int,
) -> tuple[bool, int | None, int | None, list[int], int, str | None]: ...
def all_symmetries() -> list[str]: ...
def validate_board(board: Board) -> None: ...
def generate_legal_moves(board: Board) -> int: ...
def legal_moves_list(board: Board) -> list[int]: ...
def is_legal_move(board: Board, square: int) -> bool: ...
def apply_move(board: Board, square: int) -> Board: ...
def apply_forced_pass(board: Board) -> Board: ...
def board_status(board: Board) -> str: ...
def disc_count(board: Board) -> tuple[int, int, int]: ...
def game_result(board: Board) -> str: ...
def final_margin_from_black(board: Board) -> int: ...
def transform_board(board: Board, sym: str) -> Board: ...
def transform_square(square: int, sym: str) -> int: ...
