import numpy as np

class Board:
    def __init__(self, black_bits: int, white_bits: int, side_to_move: str) -> None: ...
    @staticmethod
    def new_initial() -> Board: ...
    @property
    def black_bits(self) -> int: ...
    @property
    def white_bits(self) -> int: ...
    @property
    def side_to_move(self) -> str: ...
    def to_bits(self) -> tuple[int, int, str]: ...

def initial_board() -> Board: ...
def board_from_bits(black_bits: int, white_bits: int, side_to_move: str) -> Board: ...
def pack_board(board: Board) -> tuple[int, int, str]: ...
def _unpack_board_parts(black_bits: int, white_bits: int, side_to_move: str) -> Board: ...
def _play_random_game_parts(
    seed: int, max_plies: int | None
) -> tuple[list[tuple[int, int, str]], list[int | None], str, int, int, bool]: ...
def _sample_reachable_positions_parts(
    seed: int, num_positions: int, min_plies: int, max_plies: int
) -> list[tuple[int, int, str]]: ...
def _supervised_examples_from_trace_parts(
    boards_bits: list[tuple[int, int, str]],
    moves: list[int | None],
    final_result: str,
    final_margin_from_black: int,
    plies_played: int,
    reached_terminal: bool,
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int]]: ...
def _supervised_examples_from_traces_parts(
    traces: list[tuple[list[tuple[int, int, str]], list[int | None], str, int, int, bool]],
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int]]: ...
def _packed_supervised_examples_from_trace_parts(
    boards_bits: list[tuple[int, int, str]],
    moves: list[int | None],
    final_result: str,
    final_margin_from_black: int,
    plies_played: int,
    reached_terminal: bool,
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]]: ...
def _packed_supervised_examples_from_traces_parts(
    traces: list[tuple[list[tuple[int, int, str]], list[int | None], str, int, int, bool]],
) -> list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]]: ...
def _prepare_planes_learning_batch_parts(
    examples: list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
def _prepare_flat_learning_batch_parts(
    examples: list[tuple[tuple[int, int, str], int, list[int | None], str, int, int]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
def _encode_planes_parts(
    board: Board,
    history: list[Board],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def _encode_planes_batch_parts(
    boards: list[Board],
    histories: list[list[Board]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def _encode_flat_features_parts(
    board: Board,
    history: list[Board],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def _encode_flat_features_batch_parts(
    boards: list[Board],
    histories: list[list[Board]],
    history_len: int,
    include_legal_mask: bool,
    include_phase_plane: bool,
    include_turn_plane: bool,
    perspective: str,
) -> np.ndarray: ...
def all_symmetries() -> list[str]: ...
def validate_board(board: Board) -> None: ...
def generate_legal_moves(board: Board) -> int: ...
def legal_moves_list(board: Board) -> list[int]: ...
def is_legal_move(board: Board, square: int) -> bool: ...
def apply_move(board: Board, square: int) -> Board: ...
def apply_forced_pass(board: Board) -> Board: ...
def board_status(board: Board) -> str: ...
def disc_count(board: Board) -> tuple[int, int, int]: ...
def game_result(board: Board) -> str: ...
def final_margin_from_black(board: Board) -> int: ...
def supervised_examples_from_trace(trace: dict) -> list[dict[str, object]]: ...
def supervised_examples_from_traces(traces: list[dict]) -> list[dict[str, object]]: ...
def packed_supervised_examples_from_trace(trace: dict) -> list[dict[str, object]]: ...
def packed_supervised_examples_from_traces(traces: list[dict]) -> list[dict[str, object]]: ...
def prepare_planes_learning_batch(examples: list[dict], config: dict) -> dict[str, np.ndarray]: ...
def prepare_flat_learning_batch(examples: list[dict], config: dict) -> dict[str, np.ndarray]: ...
def encode_planes(board: Board, history: list[Board], config: dict) -> np.ndarray: ...
def encode_planes_batch(
    boards: list[Board], histories: list[list[Board]], config: dict
) -> np.ndarray: ...
def encode_flat_features(board: Board, history: list[Board], config: dict) -> np.ndarray: ...
def encode_flat_features_batch(
    boards: list[Board], histories: list[list[Board]], config: dict
) -> np.ndarray: ...
def transform_board(board: Board, sym: str) -> Board: ...
def transform_square(square: int, sym: str) -> int: ...
