class Board:
    def __init__(self, black_bits: int, white_bits: int, side_to_move: str) -> None: ...
    @staticmethod
    def new_initial() -> Board: ...
    @property
    def black_bits(self) -> int: ...
    @property
    def white_bits(self) -> int: ...
    @property
    def side_to_move(self) -> str: ...
    def to_bits(self) -> tuple[int, int, str]: ...

def initial_board() -> Board: ...
def board_from_bits(black_bits: int, white_bits: int, side_to_move: str) -> Board: ...
def all_symmetries() -> list[str]: ...
def validate_board(board: Board) -> None: ...
def generate_legal_moves(board: Board) -> int: ...
def legal_moves_list(board: Board) -> list[int]: ...
def is_legal_move(board: Board, square: int) -> bool: ...
def apply_move(board: Board, square: int) -> Board: ...
def apply_forced_pass(board: Board) -> Board: ...
def board_status(board: Board) -> str: ...
def disc_count(board: Board) -> tuple[int, int, int]: ...
def game_result(board: Board) -> str: ...
def final_margin_from_black(board: Board) -> int: ...
def transform_board(board: Board, sym: str) -> Board: ...
def transform_square(square: int, sym: str) -> int: ...
